---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kingdom/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R themes $DEPLOYPATH
    - /bin/cp -f *.php $DEPLOYPATH
    - /bin/cp -f robots.txt $DEPLOYPATH
    - /bin/cp -f sitemap.xml $DEPLOYPATH
